# Generated by Django 4.2.30 on 2026-05-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expensave_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('initials', models.CharField(blank=True, max_length=5)),
                ('profile_color', models.CharField(choices=[('accent', 'Blue'), ('warning', 'Orange'), ('danger', 'Red'), ('success', 'Indigo'), ('graphite', 'Graphite')], default=expensave_auth.models._random_color, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
